[package]
name = "flame"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]

[dependencies]
array-queue = "0.2"
docopt = "0.8"
futures-await = "0.1"
futures-black-hole = "0.2"
futures-cpupool = "0.1"
hamt-sync = "0.1"
lazy_static = "1"
pest = "1"
pest_derive = "1"
