[package]
name = "coel"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]

[dependencies]
array-queue = "0.2"
futures-await = "0.1"
futures-black-hole = "0.1"
hamt-sync = "0.1"
pest = "1"
pest_derive = "1"
