version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    environment:
      - RUSTFLAGS: -C link-dead-code
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt update --fix-missing
            apt install -y cmake
      - run:
          name: Build
          command: |
            cargo build
            cargo build --release
      - run:
          name: Test
          command: cargo test
      - run:
          name: Benchmark
          command: cargo bench
      - run:
          name: Report
          command: |
            wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
            tar xf master.tar.gz
            mkdir kcov-master/build
            cd $_
            cmake ..
            make
            make install
            cd ../..
            rm -r kcov-master
            for file in target/debug/flame-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done
            bash <(curl -s https://codecov.io/bash)
